[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "vs_undistort"
version = "2.3.0"
description = "Distortion, wobble, warp, turbulance, or heat haze removal for VapourSynth."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "pifroggi" }]

keywords = [
	"vapoursynth",
	"video",
	"distortion",
	"turbulence",
	"heat haze",
	"wobble",
	"rectification",
	"restoration",
	"filtering",
	"tensorrt",
]

classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Multimedia :: Video",
    "Environment :: GPU",
]

dependencies = [
	"vapoursynth>=74",
    "vapoursynth-mlrt-trt>=16.0",
    "tensorrt-cu13>=11.1.0.106",
	"cuda-python",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/pifroggi/vs_undistort"
Repository = "https://github.com/pifroggi/vs_undistort"
Issues = "https://github.com/pifroggi/vs_undistort/issues"
